image:
  file: .gitpod.Dockerfile

tasks:
  - init: docker-compose up -d

ports:
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 3306
    onOpen: ignore
    visibility: private
 
vscode:
  extensions:
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg