image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      docker-compose up -d
      docker exec -i pgadmin4 mkdir /var/lib/pgadmin/storage/admin_comp520.com
      docker exec -i pgadmin4 cp -r databases/ /var/lib/pgadmin/storage/admin_comp520.com

ports:
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 3306
    onOpen: ignore
    visibility: private
 
vscode:
  extensions:
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg